export enum View {
  LOGIN = 'LOGIN',
  ROLE_SELECT = 'ROLE_SELECT',
  DASHBOARD = 'DASHBOARD',
  ORDER_CUSTOMER = 'ORDER_CUSTOMER',
  ORDER_SERVICE = 'ORDER_SERVICE',
  ORDER_DETAIL = 'ORDER_DETAIL',
  PAYMENT = 'PAYMENT',
  FEEDBACK = 'FEEDBACK',
  // Operational List Views
  ORDER_HANDOVER = 'ORDER_HANDOVER',
  RETURN_OUT = 'RETURN_OUT',
  RETURN_IN = 'RETURN_IN',
  SHIPMENT_OUT = 'SHIPMENT_OUT',
  SHIPMENT_IN = 'SHIPMENT_IN',
  CARD_REQUEST = 'CARD_REQUEST',
  DAY_OPEN = 'DAY_OPEN',
  DAY_CLOSE = 'DAY_CLOSE',
  CASH_SUBMIT = 'CASH_SUBMIT',
  CANCEL_CLOSE = 'CANCEL_CLOSE',
}

export interface User {
  name: string;
  role: string;
  avatar?: string;
}
