export enum View {
  LOGIN = 'LOGIN',
  ROLE_SELECT = 'ROLE_SELECT',
  DASHBOARD = 'DASHBOARD',
  ORDER_CUSTOMER = 'ORDER_CUSTOMER',
  ORDER_HANDOVER = 'ORDER_HANDOVER',
  RETURN_MANAGEMENT = 'RETURN_MANAGEMENT',
  SHIPMENT_MANAGEMENT = 'SHIPMENT_MANAGEMENT',
  CARD_REQUEST = 'CARD_REQUEST',
  DAY_MANAGEMENT = 'DAY_MANAGEMENT',
  CASH_SUBMIT = 'CASH_SUBMIT',
  CASH_REPORT = 'CASH_REPORT',
  // Steps within Order flow
  ORDER_SERVICE = 'ORDER_SERVICE',
  ORDER_DETAIL = 'ORDER_DETAIL',
  PAYMENT = 'PAYMENT',
}

export interface User {
  name: string;
  role: string;
  avatar?: string;
}